import io
import time
from typing import Any, Dict, List, Optional
import pandas as pd


def generate_executive_html_report(
    title: str,
    dataset_name: str,
    profile: Dict[str, Any],
    kpis: List[Dict[str, Any]],
    anomalies: List[Dict[str, Any]],
    executive_summary: Dict[str, Any],
    author: str = "InsightOps AI Analyst"
) -> str:
    """
    Generates a high-resolution, print-ready HTML executive report document
    that can be viewed in browser, printed to PDF, or dispatched via scheduled email.
    """
    gen_time = time.strftime("%B %d, %Y at %H:%M UTC", time.gmtime())
    
    kpis_html = ""
    for kpi in kpis[:4]:
        trend_arrow = "▲" if kpi.get("trend") in ["up", "positive"] else ("▼" if kpi.get("trend") in ["down", "negative"] else "■")
        trend_color = "#10b981" if kpi.get("trend") in ["up", "positive"] else "#f59e0b"
        kpis_html += f"""
        <div style="background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 16px; flex: 1; min-width: 180px;">
            <div style="color: #94a3b8; font-size: 11px; text-transform: uppercase; font-weight: 600; letter-spacing: 0.05em;">{kpi.get('label')}</div>
            <div style="color: #f8fafc; font-size: 24px; font-weight: 700; margin: 4px 0;">{kpi.get('value')}</div>
            <div style="color: {trend_color}; font-size: 12px; font-weight: 500;">{trend_arrow} {kpi.get('change', 'Neutral baseline')}</div>
        </div>
        """

    anomalies_html = ""
    for anom in anomalies[:5]:
        sev_color = "#ef4444" if anom.get("severity") == "critical" else ("#f59e0b" if anom.get("severity") == "high" else "#3b82f6")
        anomalies_html += f"""
        <tr style="border-bottom: 1px solid #334155;">
            <td style="padding: 10px; color: #f8fafc; font-weight: 600;">{anom.get('title')}</td>
            <td style="padding: 10px; color: #94a3b8;">{anom.get('metric')}</td>
            <td style="padding: 10px; color: #f8fafc;">{anom.get('observed')}</td>
            <td style="padding: 10px;"><span style="background: {sev_color}22; color: {sev_color}; padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 700;">{anom.get('severity', 'medium').upper()}</span></td>
            <td style="padding: 10px; color: #cbd5e1; font-size: 12px;">{anom.get('explanation')}</td>
        </tr>
        """

    takeaways_html = "".join([f"<li style='margin-bottom: 8px; color: #cbd5e1;'>{t}</li>" for t in executive_summary.get("key_takeaways", [])])
    recs_html = ""
    for r in executive_summary.get("recommendations", []):
        recs_html += f"""
        <div style="margin-bottom: 12px; padding: 12px; background: #1e293b; border-left: 4px solid #e6c348; border-radius: 4px;">
            <strong style="color: #e6c348; font-size: 12px; display: block;">{r.get('priority')} · Owner: {r.get('owner')}</strong>
            <div style="color: #f8fafc; font-weight: 600; margin: 2px 0;">{r.get('action')}</div>
            <p style="color: #94a3b8; font-size: 12px; margin: 4px 0 0;">{r.get('rationale')}</p>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title} — Executive Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0b0f17; color: #f8fafc; margin: 0; padding: 40px; }}
        .report-card {{ max-width: 900px; margin: 0 auto; background: #0f172a; border: 1px solid #1e293b; border-radius: 12px; padding: 36px; box-shadow: 0 20px 50px rgba(0,0,0,0.5); }}
        .header {{ display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 1px solid #334155; padding-bottom: 20px; margin-bottom: 24px; }}
        h1 {{ margin: 0 0 6px 0; font-size: 26px; color: #f8fafc; }}
        .badge {{ background: #e6c34822; color: #e6c348; border: 1px solid #e6c34844; padding: 4px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; }}
        .section-title {{ font-size: 16px; font-weight: 700; color: #e6c348; margin: 28px 0 12px 0; text-transform: uppercase; letter-spacing: 0.05em; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 10px; }}
        th {{ text-align: left; padding: 10px; background: #1e293b; color: #94a3b8; font-weight: 600; }}
        @media print {{ body {{ background: #fff; color: #000; padding: 0; }} .report-card {{ box-shadow: none; border: none; padding: 0; }} }}
    </style>
</head>
<body>
    <div class="report-card">
        <div class="header">
            <div>
                <span class="badge">INSIGHTOPS AI EXECUTIVE REPORT</span>
                <h1 style="margin-top: 8px;">{title}</h1>
                <p style="margin: 0; color: #94a3b8; font-size: 13px;">Dataset: <b>{dataset_name}</b> · Generated by {author}</p>
            </div>
            <div style="text-align: right; color: #64748b; font-size: 12px;">
                <div>{gen_time}</div>
                <div style="margin-top: 4px;"><span style="color: #10b981; font-weight: 600;">● Verified Deterministic Analytics</span></div>
            </div>
        </div>

        <div class="section-title">1. Executive Summary & Takeaways</div>
        <p style="font-size: 14px; line-height: 1.6; color: #e2e8f0; background: #1e293b; padding: 16px; border-radius: 8px;">
            {executive_summary.get('executive_summary')}
        </p>
        <ul style="padding-left: 20px; margin: 12px 0 20px;">
            {takeaways_html}
        </ul>

        <div class="section-title">2. Key Performance Indicators</div>
        <div style="display: flex; gap: 14px; flex-wrap: wrap;">
            {kpis_html}
        </div>

        <div class="section-title">3. Operational Risk Radar & Outliers</div>
        <table>
            <thead>
                <tr><th>Incident Title</th><th>Metric</th><th>Observed</th><th>Severity</th><th>Statistical Detail</th></tr>
            </thead>
            <tbody>
                {anomalies_html if anomalies else '<tr><td colspan="5" style="padding: 16px; text-align: center; color: #64748b;">No critical anomalies detected in active dataset.</td></tr>'}
            </tbody>
        </table>

        <div class="section-title">4. Strategic Recommendations</div>
        {recs_html}

        <div style="margin-top: 36px; padding-top: 16px; border-top: 1px solid #334155; text-align: center; color: #64748b; font-size: 11px;">
            Confidential · Generated by InsightOps AI Enterprise Decision Platform · 100% Traceable Mathematical Calculations
        </div>
    </div>
</body>
</html>
"""
    return html
